### ISSUE TITLE
Make site-wide search enhancements

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#412]
Proposition: Improve site-wide search. Do through either 1) enhancing the built-in search capabilities or 2) incorporating a Google programmable search engine (https://programmablesearchengine.google.com/about/).

- [x] Add dataset metadata (e.g. names, slugs) to search results (e.g. searching 'wsc' should return the Wisconsin Sleep Cohort at the top)
- [ ] Search dataset documentation (e.g. filenames and contents) (e.g. searching 'mesa montage' should return https://sleepdata.org/datasets/mesa/pages/equipment/montage-and-sampling-rate-information.md)
- [ ] Allow search cache to be refreshed from web application itself (e.g. not just SSH'd to server, ref #362)
- [ ] Allow 'special' search results (?) to be added/edited through the web interface, e.g. when searching 'SHHS' this callout box shows up that points to the dataset, https://sleepdata.org/search?from=&search=shhs 
- [x] For variable results shown (e.g. search 'ahi_'), byline could read "in ABC Variables" instead of just "in ABC".
- [x] Add filterable options on search results page, e.g. to filter to results by Forum, Documentation, Datasets, Variables (#374 made this possible for filtering to only forum results)

Example searches:
https://sleepdata.org/search?from=&search=wsc (only returning variables; not dataset)
https://www.google.com/search?q=sleepdata.org%3A+wsc (main dataset index page top hit)

https://sleepdata.org/search?from=&search=mesa+montage (a couple forum hits)
https://www.google.com/search?q=sleepdata.org%3A+mesa+montage (mesa montage markdown documentation top hit)

**Comment by remomueller** [comment]
Just to clarify the item for resetting the search cache, it shouldn't be necessary to do (only after code pushes), as it mainly impacts cached results that aren't populated due to changes in what is being indexed for a particular model (variable/dataset, etc). When a model updates in the database (either from a spout deploy, or other change), the fact that it gets updated in the db makes the site wide search re-index it. For the dataset documentation, I'll have a cron job that rescans the documentation on a daily basis, so that will stay up to date as well.

**Comment by remomueller** [comment]
- [ ] Allow search cache to be refreshed from web application itself (e.g. not just SSH'd to server, ref #362)

This one has been addressed by adding a weekly cronjob.

**Comment by remomueller** [comment]
Did not implement this one:

- [ ] Allow 'special' search results (?) to be added/edited through the web interface, e.g. when searching 'SHHS' this callout box shows up that points to the dataset, https://sleepdata.org/search?from=&search=shhs

If you still want this one, suggest creating a new dedicated issue for that one.

**Comment by remomueller** [comment]
- [ ] Search dataset documentation (e.g. filenames and contents) (e.g. searching 'mesa montage' should return https://sleepdata.org/datasets/mesa/pages/equipment/montage-and-sampling-rate-information.md)

For this one, I may need to do a tweak to allow it to include the dataset slug in the search as well, although it may clutter as typing "mesa" may then return every page of documentation for it. Let me know if the search feels better and if you still want me to make further tweaks to accommodate this particular request.

**Comment by remomueller** [comment]
Final note, dataset pages get re-indexed daily, so if you push new updates, they may not reflect in search until 24 hours later.
